### PR TITLE
Temp fix to get KMeans unit tests to pass.

### LINKED ISSUE #117: KMeansUpdateIT fails / hangs
`KMeansUpdateIT` is disabled right now since it mysteriously hangs if you run it. The second call to `KMeans.train` never returns. I find that it doesn't seem to get scheduled even since the last thing in the logs is the call to `train`, and the Spark UI just shows the parent `foreachRDD` from `BatchLayer` executing -- in my case, I see it's stuck at 8 / 18 partitions.

Suneel has been investigating but I am current looking at it too.

### PR DESCRIPTION
**Pull request by smarthi**
Fixes #117

### CODE REVIEW

File: oryx-app-mllib/src/test/java/com/cloudera/oryx/app/mllib/kmeans/KMeansUpdateIT.java [hunk 1]
```diff
@@ -58,8 +56,8 @@ public void testKMeans() throws Exception {
     overlayConfig.put("oryx.batch.streaming.generation-interval-sec", GEN_INTERVAL_SEC);
     overlayConfig.put("oryx.batch.streaming.block-interval-sec", BLOCK_INTERVAL_SEC);
     overlayConfig.put("oryx.kmeans.hyperparams.k", CLUSTERS);
-    overlayConfig.put("oryx.input-schema.num-features", 2);
-    overlayConfig.put("oryx.input-schema.numeric-features", "[\"0\",\"1\"]");
+    overlayConfig.put("oryx.input-schema.num-features", 5);
+    overlayConfig.put("oryx.input-schema.numeric-features", "[\"0\",\"1\",\"2\",\"3\",\"4\"]");
```
Comment (srowen) [inline oryx-app-mllib/src/test/java/com/cloudera/oryx/app/mllib/kmeans/KMeansUpdateIT.java]: Don't bother changing this, but you can also set cateogrical-features = [] to imply that everything is numeric. Yes this change is just fine of course.

Comment (smarthi) [inline oryx-app-mllib/src/test/java/com/cloudera/oryx/app/mllib/kmeans/KMeansUpdateIT.java]: Will do, in next PR.
